<a href="https://colab.research.google.com/github/pvarun2005/Depression-Detector/blob/main/Regeneron_STS_Code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files


uploaded = files.upload()

Saving Student Mental health.csv to Student Mental health.csv

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import RFE
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import KFold

mhdata = pd.read_csv("Student Mental health.csv")

In [ ]:
mhdata.head()

,Timestamp,Choose your gender,Age,What is your course?,Your current year of Study,What is your CGPA?,Marital status,Do you have Depression?,Do you have Anxiety?,Do you have Panic attack?,Did you seek any specialist for a treatment?
0,8/7/2020 12:02,Female,18.0,Engineering,year 1,3.00 - 3.49,No,Yes,No,Yes,No
1,8/7/2020 12:04,Male,21.0,Islamic education,year 2,3.00 - 3.49,No,No,Yes,No,No
2,8/7/2020 12:05,Male,19.0,BIT,Year 1,3.00 - 3.49,No,Yes,Yes,Yes,No
3,8/7/2020 12:06,Female,22.0,Laws,year 3,3.00 - 3.49,Yes,Yes,No,No,No
4,8/7/2020 12:13,Male,23.0,Mathemathics,year 4,3.00 - 3.49,No,No,No,No,No

In [ ]:
mhdata.isnull().sum()

Timestamp                                       0
Choose your gender                              0
Age                                             1
What is your course?                            0
Your current year of Study                      0
What is your CGPA?                              0
Marital status                                  0
Do you have Depression?                         0
Do you have Anxiety?                            0
Do you have Panic attack?                       0
Did you seek any specialist for a treatment?    0
dtype: int64

In [ ]:
mean = mhdata['Age'].mean()
mhdata['Age'] = mhdata['Age'].fillna(value=mean)

In [ ]:
mhdata = mhdata.drop('Timestamp', axis = 1)

In [ ]:
mhdata.head()

,Choose your gender,Age,What is your course?,Your current year of Study,What is your CGPA?,Marital status,Do you have Depression?,Do you have Anxiety?,Do you have Panic attack?,Did you seek any specialist for a treatment?
0,Female,18.0,Engineering,year 1,3.00 - 3.49,No,Yes,No,Yes,No
1,Male,21.0,Islamic education,year 2,3.00 - 3.49,No,No,Yes,No,No
2,Male,19.0,BIT,Year 1,3.00 - 3.49,No,Yes,Yes,Yes,No
3,Female,22.0,Laws,year 3,3.00 - 3.49,Yes,Yes,No,No,No
4,Male,23.0,Mathemathics,year 4,3.00 - 3.49,No,No,No,No,No

In [ ]:
mhdata['What is your course?'].value_counts()

BCS                        18
Engineering                17
BIT                        10
Biomedical science          4
KOE                         4
BENL                        2
Laws                        2
psychology                  2
Engine                      2
Islamic Education           1
Biotechnology               1
engin                       1
Econs                       1
MHSC                        1
Malcom                      1
Kop                         1
Human Sciences              1
Communication               1
Nursing                     1
Diploma Nursing             1
IT                          1
Pendidikan Islam            1
Radiography                 1
Fiqh fatwa                  1
DIPLOMA TESL                1
Koe                         1
Fiqh                        1
CTS                         1
koe                         1
Benl                        1
Kirkhs                      1
Mathemathics                1
Pendidikan islam            1
Human Resources             1
Irkhs                       1
Psychology                  1
KENMS                       1
Accounting                  1
ENM                         1
Marine science              1
Banking Studies             1
Business Administration     1
Law                         1
KIRKHS                      1
Usuluddin                   1
TAASL                       1
ALA                         1
Islamic education           1
Pendidikan Islam            1
Name: What is your course?, dtype: int64

In [ ]:
mhdata.at[mhdata.index[47],'What is your course?'] = 'Engineering'
mhdata.at[mhdata.index[64],'What is your course?'] = 'Engineering'
mhdata.at[mhdata.index[63],'What is your course?'] = 'Engineering'
mhdata.at[mhdata.index[3],'What is your course?'] = 'Law'
mhdata.at[mhdata.index[71],'What is your course?'] = 'Law'
mhdata.at[mhdata.index[53],'What is your course?'] = 'KOE'
mhdata.at[mhdata.index[91],'What is your course?'] = 'KOE'
mhdata.at[mhdata.index[86],'What is your course?'] = 'FIQH'
mhdata.at[mhdata.index[78],'What is your course?'] = 'BIT'
mhdata.at[mhdata.index[81],'What is your course?'] = 'Nursing'
mhdata.at[mhdata.index[85],'What is your course?'] = 'Psychology'
mhdata.at[mhdata.index[87],'What is your course?'] = 'Psychology'
mhdata.at[mhdata.index[94],'What is your course?'] = 'FIQH'
mhdata.at[mhdata.index[92],'What is your course?'] = 'Islamic Education'
mhdata.at[mhdata.index[83],'What is your course?'] = 'Islamic Education'
mhdata.at[mhdata.index[56],'What is your course?'] = 'KIRKHS'
mhdata.at[mhdata.index[90],'What is your course?'] = 'TESL'
mhdata.at[mhdata.index[9],'What is your course?'] = 'KIRKHS'
mhdata.at[mhdata.index[6],'What is your course?'] = 'Islamic Education'
mhdata.at[mhdata.index[1],'What is your course?'] = 'Islamic Education'
mhdata.at[mhdata.index[17],'What is your course?'] = 'KENMS'
mhdata.at[mhdata.index[59],'What is your course?'] = 'BENL'
mhdata.at[mhdata.index[99],'What is your course?'] = 'Islamic Education'
mhdata.at[mhdata.index[98],'What is your course?'] = 'Nursing'
mhdata.at[mhdata.index[81],'What is your course?'] = 'Nursing'

In [ ]:
mhdata['What is your course?'].value_counts()

Engineering                20
BCS                        18
BIT                        11
Islamic Education           6
KOE                         5
Biomedical science          4
Law                         3
BENL                        3
KIRKHS                      3
Psychology                  3
Nursing                     2
KENMS                       2
FIQH                        2
Communication               1
CTS                         1
Human Sciences              1
Kop                         1
Malcom                      1
MHSC                        1
Radiography                 1
Econs                       1
TAASL                       1
IT                          1
ALA                         1
Usuluddin                   1
Business Administration     1
Banking Studies             1
Marine science              1
Accounting                  1
Human Resources             1
Mathemathics                1
TESL                        1
Name: What is your course?, dtype: int64

In [ ]:
mhdata.dtypes

Choose your gender                               object
Age                                             float64
What is your course?                             object
Your current year of Study                       object
What is your CGPA?                               object
Marital status                                   object
Do you have Depression?                          object
Do you have Anxiety?                             object
Do you have Panic attack?                        object
Did you seek any specialist for a treatment?     object
dtype: object

In [ ]:
encoder= LabelEncoder()
mhdata["Choose your gender"]=encoder.fit_transform(mhdata["Choose your gender"])
mhdata["What is your course?"]=encoder.fit_transform(mhdata["What is your course?"])
mhdata["Your current year of Study"]=encoder.fit_transform(mhdata["Your current year of Study"])
mhdata["What is your CGPA?"]=encoder.fit_transform(mhdata["What is your CGPA?"])
mhdata["Marital status"]=encoder.fit_transform(mhdata["Marital status"])
mhdata["Do you have Depression?"]=encoder.fit_transform(mhdata["Do you have Depression?"])
mhdata["Do you have Anxiety?"]=encoder.fit_transform(mhdata["Do you have Anxiety?"])
mhdata["Do you have Panic attack?"]=encoder.fit_transform(mhdata["Do you have Panic attack?"])
mhdata["Did you seek any specialist for a treatment?"]=encoder.fit_transform(mhdata["Did you seek any specialist for a treatment?"])

In [ ]:
mhdata

,Choose your gender,Age,What is your course?,Your current year of Study,What is your CGPA?,Marital status,Do you have Depression?,Do you have Anxiety?,Do you have Panic attack?,Did you seek any specialist for a treatment?
0,0,18.0,11,3,3,0,1,0,1,0
1,1,21.0,16,4,3,0,0,1,0,0
2,1,19.0,4,0,3,0,1,1,1,0
3,0,22.0,21,5,3,1,1,0,0,0
4,1,23.0,25,6,3,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
96,0,21.0,2,3,4,0,0,1,0,0
97,1,18.0,11,1,3,0,1,1,0,0
98,0,19.0,26,2,4,1,1,0,1,0
99,0,23.0,16,6,4,0,0,0,0,0
100,1,20.0,6,1,3,0,0,0,0,0

In [ ]:
mhdata.dtypes

Choose your gender                                int64
Age                                             float64
What is your course?                              int64
Your current year of Study                        int64
What is your CGPA?                                int64
Marital status                                    int64
Do you have Depression?                           int64
Do you have Anxiety?                              int64
Do you have Panic attack?                         int64
Did you seek any specialist for a treatment?      int64
dtype: object

In [ ]:
X = mhdata.drop('Do you have Depression?', axis=1)
target = mhdata['Do you have Depression?']
print(X)

     Choose your gender   Age  What is your course?  \
0                     0  18.0                    11
1                     1  21.0                    16
2                     1  19.0                     4
3                     0  22.0                    21
4                     1  23.0                    25
..                  ...   ...                   ...
96                    0  21.0                     2
97                    1  18.0                    11
98                    0  19.0                    26
99                    0  23.0                    16
100                   1  20.0                     6

     Your current year of Study  What is your CGPA?  Marital status  \
0                             3                   3               0
1                             4                   3               0
2                             0                   3               0
3                             5                   3               1
4                             6                   3               0
..                          ...                 ...             ...
96                            3                   4               0
97                            1                   3               0
98                            2                   4               1
99                            6                   4               0
100                           1                   3               0

     Do you have Anxiety?  Do you have Panic attack?  \
0                       0                          1
1                       1                          0
2                       1                          1
3                       0                          0
4                       0                          0
..                    ...                        ...
96                      1                          0
97                      1                          0
98                      0                          1
99                      0                          0
100                     0                          0

     Did you seek any specialist for a treatment?
0                                               0
1                                               0
2                                               0
3                                               0
4                                               0
..                                            ...
96                                              0
97                                              0
98                                              0
99                                              0
100                                             0

[101 rows x 9 columns]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, target, test_size=0.2, random_state=0)
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
logreg = LogisticRegression()
logreg.fit(X_train, y_train)
y_pred = logreg.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print('Accuracy of logistic regression classifier on test set: {:.4f}'.format(logreg.score(X_test, y_test)))

[[13  2]
 [ 3  3]]
              precision    recall  f1-score   support

           0       0.81      0.87      0.84        15
           1       0.60      0.50      0.55         6

    accuracy                           0.76        21
   macro avg       0.71      0.68      0.69        21
weighted avg       0.75      0.76      0.75        21

Accuracy of logistic regression classifier on test set: 0.7619

In [ ]:
svm=SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)
y_pred = svm.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print('Accuracy of SVM classifier on test set: {:.4f}'.format(svm.score(X_test, y_test)))

[[15  0]
 [ 3  3]]
              precision    recall  f1-score   support

           0       0.83      1.00      0.91        15
           1       1.00      0.50      0.67         6

    accuracy                           0.86        21
   macro avg       0.92      0.75      0.79        21
weighted avg       0.88      0.86      0.84        21

Accuracy of SVM classifier on test set: 0.8571

In [ ]:
dtree=DecisionTreeClassifier()
dtree.fit(X_train,y_train)
dtree.score(X_test,y_test)
y_pred = dtree.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print('Accuracy of decision tree classifier on test set: {:.4f}'.format(dtree.score(X_test, y_test)))

[[12  3]
 [ 3  3]]
              precision    recall  f1-score   support

           0       0.80      0.80      0.80        15
           1       0.50      0.50      0.50         6

    accuracy                           0.71        21
   macro avg       0.65      0.65      0.65        21
weighted avg       0.71      0.71      0.71        21

Accuracy of decision tree classifier on test set: 0.7143

In [ ]:
randomForest= RandomForestClassifier(n_estimators=100,)
randomForest.fit(X_train,y_train)
randomForest.score(X_test,y_test)
y_pred = randomForest.predict(X_test)
print("Confusion matrix\n",confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print('Accuracy of random forest classifier on test set: {:.4f}'.format(randomForest.score(X_test, y_test)))

Confusion matrix
 [[15  0]
 [ 2  4]]
              precision    recall  f1-score   support

           0       0.88      1.00      0.94        15
           1       1.00      0.67      0.80         6

    accuracy                           0.90        21
   macro avg       0.94      0.83      0.87        21
weighted avg       0.92      0.90      0.90        21

Accuracy of random forest classifier on test set: 0.9048

In [ ]:
def KFoldCrossValidation(X, y, k = 5):
  num_examples = len(X)
  kwargs = {"a": len(X), "size": len(X), "replace": False}
  samples = np.random.choice(**kwargs)

  size_block = int(len(X) / k)
  for i in range(k):
    start_index = i * size_block
    end_index = (i + 1) * size_block
    sample_indices = samples[start_index: end_index]

    X_test = X.loc[sample_indices, :]
    y_test = y[sample_indices]

    train_sample_indices = []
    for i in range(len(X)):
      if i not in sample_indices:
        train_sample_indices.append(i)

    X_train = X.loc[train_sample_indices, :]
    y_train = y[train_sample_indices]

    logreg = LogisticRegression(class_weight='balanced')
    logreg.fit(X_train, y_train)
    y_pred = logreg.predict(X_test)
    print(confusion_matrix(y_test,y_pred))
    print(classification_report(y_test,y_pred))
    print('Accuracy of logistic regression classifier on test set: {:.4f}'.format(logreg.score(X_test, y_test)))

In [ ]:
KFoldCrossValidation(X, target)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,

[[11  3]
 [ 3  3]]
              precision    recall  f1-score   support

           0       0.79      0.79      0.79        14
           1       0.50      0.50      0.50         6

    accuracy                           0.70        20
   macro avg       0.64      0.64      0.64        20
weighted avg       0.70      0.70      0.70        20

Accuracy of logistic regression classifier on test set: 0.7000
[[12  0]
 [ 3  5]]
              precision    recall  f1-score   support

           0       0.80      1.00      0.89        12
           1       1.00      0.62      0.77         8

    accuracy                           0.85        20
   macro avg       0.90      0.81      0.83        20
weighted avg       0.88      0.85      0.84        20

Accuracy of logistic regression classifier on test set: 0.8500
[[10  3]
 [ 3  4]]
              precision    recall  f1-score   support

           0       0.77      0.77      0.77        13
           1       0.57      0.57      0.57         7

    accuracy                           0.70        20
   macro avg       0.67      0.67      0.67        20
weighted avg       0.70      0.70      0.70        20

Accuracy of logistic regression classifier on test set: 0.7000
[[8 3]
 [3 6]]
              precision    recall  f1-score   support

           0       0.73      0.73      0.73        11
           1       0.67      0.67      0.67         9

    accuracy                           0.70        20
   macro avg       0.70      0.70      0.70        20
weighted avg       0.70      0.70      0.70        20

Accuracy of logistic regression classifier on test set: 0.7000
[[14  1]
 [ 1  4]]
              precision    recall  f1-score   support

           0       0.93      0.93      0.93        15
           1       0.80      0.80      0.80         5

    accuracy                           0.90        20
   macro avg       0.87      0.87      0.87        20
weighted avg       0.90      0.90      0.90        20

Accuracy of logistic regression classifier on test set: 0.9000

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,